/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package com.treefinance.saas.taskcenter.dto;

import java.io.Serializable;
import java.util.Date;

public class AppCallbackConfigDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table app_callback_config
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.Id
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.AppId
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private String appId;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.receiver
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private String receiver;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.version
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte version;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.isNewKey
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte isNewKey;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.Url
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private String url;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.retryTimes
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte retryTimes;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.timeOut
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte timeOut;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.remark
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private String remark;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.isNotifyCancel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte isNotifyCancel;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.isNotifyFailure
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte isNotifyFailure;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.isNotifySuccess
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte isNotifySuccess;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.notifyModel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte notifyModel;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.dataType
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Byte dataType;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.CreateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Date createTime;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * app_callback_config.LastUpdateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.Id
     *
     * @return the value of app_callback_config.Id
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.Id
     *
     * @param id the value for app_callback_config.Id
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.AppId
     *
     * @return the value of app_callback_config.AppId
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.AppId
     *
     * @param appId the value for app_callback_config.AppId
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.receiver
     *
     * @return the value of app_callback_config.receiver
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.receiver
     *
     * @param receiver the value for app_callback_config.receiver
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.version
     *
     * @return the value of app_callback_config.version
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.version
     *
     * @param version the value for app_callback_config.version
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setVersion(Byte version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.isNewKey
     *
     * @return the value of app_callback_config.isNewKey
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getIsNewKey() {
        return isNewKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.isNewKey
     *
     * @param isNewKey the value for app_callback_config.isNewKey
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setIsNewKey(Byte isNewKey) {
        this.isNewKey = isNewKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.Url
     *
     * @return the value of app_callback_config.Url
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.Url
     *
     * @param url the value for app_callback_config.Url
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.retryTimes
     *
     * @return the value of app_callback_config.retryTimes
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.retryTimes
     *
     * @param retryTimes the value for app_callback_config.retryTimes
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setRetryTimes(Byte retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.timeOut
     *
     * @return the value of app_callback_config.timeOut
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.timeOut
     *
     * @param timeOut the value for app_callback_config.timeOut
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setTimeOut(Byte timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.remark
     *
     * @return the value of app_callback_config.remark
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.remark
     *
     * @param remark the value for app_callback_config.remark
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.isNotifyCancel
     *
     * @return the value of app_callback_config.isNotifyCancel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getIsNotifyCancel() {
        return isNotifyCancel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.isNotifyCancel
     *
     * @param isNotifyCancel the value for app_callback_config.isNotifyCancel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setIsNotifyCancel(Byte isNotifyCancel) {
        this.isNotifyCancel = isNotifyCancel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.isNotifyFailure
     *
     * @return the value of app_callback_config.isNotifyFailure
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getIsNotifyFailure() {
        return isNotifyFailure;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.isNotifyFailure
     *
     * @param isNotifyFailure the value for app_callback_config.isNotifyFailure
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setIsNotifyFailure(Byte isNotifyFailure) {
        this.isNotifyFailure = isNotifyFailure;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.isNotifySuccess
     *
     * @return the value of app_callback_config.isNotifySuccess
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getIsNotifySuccess() {
        return isNotifySuccess;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.isNotifySuccess
     *
     * @param isNotifySuccess the value for app_callback_config.isNotifySuccess
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setIsNotifySuccess(Byte isNotifySuccess) {
        this.isNotifySuccess = isNotifySuccess;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.notifyModel
     *
     * @return the value of app_callback_config.notifyModel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getNotifyModel() {
        return notifyModel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.notifyModel
     *
     * @param notifyModel the value for app_callback_config.notifyModel
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setNotifyModel(Byte notifyModel) {
        this.notifyModel = notifyModel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.dataType
     *
     * @return the value of app_callback_config.dataType
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Byte getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.dataType
     *
     * @param dataType the value for app_callback_config.dataType
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setDataType(Byte dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.CreateTime
     *
     * @return the value of app_callback_config.CreateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.CreateTime
     *
     * @param createTime the value for app_callback_config.CreateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * app_callback_config.LastUpdateTime
     *
     * @return the value of app_callback_config.LastUpdateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * app_callback_config.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_callback_config.LastUpdateTime
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Thu Sep 28 20:41:02 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", receiver=").append(receiver);
        sb.append(", version=").append(version);
        sb.append(", isNewKey=").append(isNewKey);
        sb.append(", url=").append(url);
        sb.append(", retryTimes=").append(retryTimes);
        sb.append(", timeOut=").append(timeOut);
        sb.append(", remark=").append(remark);
        sb.append(", isNotifyCancel=").append(isNotifyCancel);
        sb.append(", isNotifyFailure=").append(isNotifyFailure);
        sb.append(", isNotifySuccess=").append(isNotifySuccess);
        sb.append(", notifyModel=").append(notifyModel);
        sb.append(", dataType=").append(dataType);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}