/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.taskcenter.dto;

import java.io.Serializable;
import java.util.Date;

public class AppLicenseDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.Id
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.AppId
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.SdkPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String sdkPublicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.SdkPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String sdkPrivateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.ServerPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String serverPublicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.ServerPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String serverPrivateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.DataSecretKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private String dataSecretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.CreateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_app_license.LastUpdateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_app_license
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.Id
     *
     * @return the value of s_app_license.Id
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.Id
     *
     * @param id the value for s_app_license.Id
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.AppId
     *
     * @return the value of s_app_license.AppId
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.AppId
     *
     * @param appId the value for s_app_license.AppId
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.SdkPublicKey
     *
     * @return the value of s_app_license.SdkPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getSdkPublicKey() {
        return sdkPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.SdkPublicKey
     *
     * @param sdkPublicKey the value for s_app_license.SdkPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setSdkPublicKey(String sdkPublicKey) {
        this.sdkPublicKey = sdkPublicKey == null ? null : sdkPublicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.SdkPrivateKey
     *
     * @return the value of s_app_license.SdkPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getSdkPrivateKey() {
        return sdkPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.SdkPrivateKey
     *
     * @param sdkPrivateKey the value for s_app_license.SdkPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setSdkPrivateKey(String sdkPrivateKey) {
        this.sdkPrivateKey = sdkPrivateKey == null ? null : sdkPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.ServerPublicKey
     *
     * @return the value of s_app_license.ServerPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getServerPublicKey() {
        return serverPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.ServerPublicKey
     *
     * @param serverPublicKey the value for s_app_license.ServerPublicKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setServerPublicKey(String serverPublicKey) {
        this.serverPublicKey = serverPublicKey == null ? null : serverPublicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.ServerPrivateKey
     *
     * @return the value of s_app_license.ServerPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getServerPrivateKey() {
        return serverPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.ServerPrivateKey
     *
     * @param serverPrivateKey the value for s_app_license.ServerPrivateKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setServerPrivateKey(String serverPrivateKey) {
        this.serverPrivateKey = serverPrivateKey == null ? null : serverPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.DataSecretKey
     *
     * @return the value of s_app_license.DataSecretKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public String getDataSecretKey() {
        return dataSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.DataSecretKey
     *
     * @param dataSecretKey the value for s_app_license.DataSecretKey
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setDataSecretKey(String dataSecretKey) {
        this.dataSecretKey = dataSecretKey == null ? null : dataSecretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.CreateTime
     *
     * @return the value of s_app_license.CreateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.CreateTime
     *
     * @param createTime the value for s_app_license.CreateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_app_license.LastUpdateTime
     *
     * @return the value of s_app_license.LastUpdateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_app_license.LastUpdateTime
     *
     * @param lastUpdateTime the value for s_app_license.LastUpdateTime
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_app_license
     *
     * @mbggenerated Wed May 10 11:40:23 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", sdkPublicKey=").append(sdkPublicKey);
        sb.append(", sdkPrivateKey=").append(sdkPrivateKey);
        sb.append(", serverPublicKey=").append(serverPublicKey);
        sb.append(", serverPrivateKey=").append(serverPrivateKey);
        sb.append(", dataSecretKey=").append(dataSecretKey);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}