package com.treefinance.saas.taskcenter.dao.mapper;

import com.treefinance.saas.taskcenter.dao.entity.TaskBuryPointLog;
import com.treefinance.saas.taskcenter.dao.entity.TaskBuryPointLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskBuryPointLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    long countByExample(TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int deleteByExample(TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int insert(TaskBuryPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int insertSelective(TaskBuryPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    List<TaskBuryPointLog> selectByExampleWithRowbounds(TaskBuryPointLogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    List<TaskBuryPointLog> selectByExample(TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    List<TaskBuryPointLog> selectPaginationByExample(TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int insertOrUpdateBySelective(TaskBuryPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    void batchInsert(List<TaskBuryPointLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    void batchUpdateByPrimaryKey(List<TaskBuryPointLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<TaskBuryPointLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    TaskBuryPointLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskBuryPointLog record, @Param("example") TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int updateByExample(@Param("record") TaskBuryPointLog record, @Param("example") TaskBuryPointLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int updateByPrimaryKeySelective(TaskBuryPointLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Tue Sep 18 11:27:31 CST 2018
     */
    int updateByPrimaryKey(TaskBuryPointLog record);
}