package com.treefinance.saas.taskcenter.dao.mapper;

import com.treefinance.saas.taskcenter.dao.entity.TaskOperatorMaintainUserLog;
import com.treefinance.saas.taskcenter.dao.entity.TaskOperatorMaintainUserLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskOperatorMaintainUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    long countByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int deleteByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int insert(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int insertSelective(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    List<TaskOperatorMaintainUserLog> selectByExampleWithRowbounds(TaskOperatorMaintainUserLogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    List<TaskOperatorMaintainUserLog> selectByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    List<TaskOperatorMaintainUserLog> selectPaginationByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int insertOrUpdateBySelective(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    void batchInsert(List<TaskOperatorMaintainUserLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    void batchUpdateByPrimaryKey(List<TaskOperatorMaintainUserLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<TaskOperatorMaintainUserLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    TaskOperatorMaintainUserLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskOperatorMaintainUserLog record, @Param("example") TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int updateByExample(@Param("record") TaskOperatorMaintainUserLog record, @Param("example") TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int updateByPrimaryKeySelective(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    int updateByPrimaryKey(TaskOperatorMaintainUserLog record);
}