package com.treefinance.saas.taskcenter.dao.mapper;

import com.treefinance.saas.taskcenter.dao.entity.TaskDevice;
import com.treefinance.saas.taskcenter.dao.entity.TaskDeviceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    long countByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int deleteByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int insert(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int insertSelective(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    List<TaskDevice> selectByExampleWithRowbounds(TaskDeviceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    List<TaskDevice> selectByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    List<TaskDevice> selectPaginationByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int insertOrUpdateBySelective(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    void batchInsert(List<TaskDevice> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    void batchUpdateByPrimaryKey(List<TaskDevice> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<TaskDevice> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    TaskDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskDevice record, @Param("example") TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int updateByExample(@Param("record") TaskDevice record, @Param("example") TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int updateByPrimaryKeySelective(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    int updateByPrimaryKey(TaskDevice record);
}