package com.treefinance.saas.taskcenter.dao.mapper;

import com.treefinance.saas.taskcenter.dao.entity.TaskSupport;
import com.treefinance.saas.taskcenter.dao.entity.TaskSupportCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    long countByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int deleteByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int insert(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int insertSelective(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    List<TaskSupport> selectByExampleWithRowbounds(TaskSupportCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    List<TaskSupport> selectByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    List<TaskSupport> selectPaginationByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int insertOrUpdateBySelective(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    void batchInsert(List<TaskSupport> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    void batchUpdateByPrimaryKey(List<TaskSupport> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<TaskSupport> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    TaskSupport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskSupport record, @Param("example") TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int updateByExample(@Param("record") TaskSupport record, @Param("example") TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int updateByPrimaryKeySelective(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbg.generated Sat Sep 29 10:21:57 CST 2018
     */
    int updateByPrimaryKey(TaskSupport record);
}