package com.treefinance.saas.taskcenter.common.model.dto;

import java.io.Serializable;
import java.util.Date;

public class AppCallbackBizDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_biz.Id
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_biz.CallbackId
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private Integer callbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_biz.BizType
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private Byte bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_biz.CreateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_callback_biz.LastUpdateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_biz.Id
     *
     * @return the value of app_callback_biz.Id
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_biz.Id
     *
     * @param id the value for app_callback_biz.Id
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_biz.CallbackId
     *
     * @return the value of app_callback_biz.CallbackId
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public Integer getCallbackId() {
        return callbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_biz.CallbackId
     *
     * @param callbackId the value for app_callback_biz.CallbackId
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public void setCallbackId(Integer callbackId) {
        this.callbackId = callbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_biz.BizType
     *
     * @return the value of app_callback_biz.BizType
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_biz.BizType
     *
     * @param bizType the value for app_callback_biz.BizType
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_biz.CreateTime
     *
     * @return the value of app_callback_biz.CreateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_biz.CreateTime
     *
     * @param createTime the value for app_callback_biz.CreateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_callback_biz.LastUpdateTime
     *
     * @return the value of app_callback_biz.LastUpdateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_callback_biz.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_callback_biz.LastUpdateTime
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", callbackId=").append(callbackId);
        sb.append(", bizType=").append(bizType);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}