package com.treefinance.saas.taskcenter.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskOperatorMaintainUserLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.id
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.taskId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.appId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.mobile
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.operatorName
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.createTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_operator_maintain_user_log.lastUpdateTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.id
     *
     * @return the value of task_operator_maintain_user_log.id
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.id
     *
     * @param id the value for task_operator_maintain_user_log.id
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.taskId
     *
     * @return the value of task_operator_maintain_user_log.taskId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.taskId
     *
     * @param taskId the value for task_operator_maintain_user_log.taskId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.appId
     *
     * @return the value of task_operator_maintain_user_log.appId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.appId
     *
     * @param appId the value for task_operator_maintain_user_log.appId
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.mobile
     *
     * @return the value of task_operator_maintain_user_log.mobile
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.mobile
     *
     * @param mobile the value for task_operator_maintain_user_log.mobile
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.operatorName
     *
     * @return the value of task_operator_maintain_user_log.operatorName
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.operatorName
     *
     * @param operatorName the value for task_operator_maintain_user_log.operatorName
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.createTime
     *
     * @return the value of task_operator_maintain_user_log.createTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.createTime
     *
     * @param createTime the value for task_operator_maintain_user_log.createTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_operator_maintain_user_log.lastUpdateTime
     *
     * @return the value of task_operator_maintain_user_log.lastUpdateTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_operator_maintain_user_log.lastUpdateTime
     *
     * @param lastUpdateTime the value for task_operator_maintain_user_log.lastUpdateTime
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbg.generated Fri Sep 28 11:34:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", appId=").append(appId);
        sb.append(", mobile=").append(mobile);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}