package com.treefinance.saas.taskcenter.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskDeviceCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected int limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected int offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public TaskDeviceCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void setOffset(int offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TaskId is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TaskId is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("TaskId =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("TaskId <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("TaskId >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TaskId >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("TaskId <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("TaskId <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("TaskId in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("TaskId not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("TaskId between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("TaskId not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNull() {
            addCriterion("ProvinceName is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNotNull() {
            addCriterion("ProvinceName is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameEqualTo(String value) {
            addCriterion("ProvinceName =", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotEqualTo(String value) {
            addCriterion("ProvinceName <>", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThan(String value) {
            addCriterion("ProvinceName >", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("ProvinceName >=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThan(String value) {
            addCriterion("ProvinceName <", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("ProvinceName <=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLike(String value) {
            addCriterion("ProvinceName like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotLike(String value) {
            addCriterion("ProvinceName not like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIn(List<String> values) {
            addCriterion("ProvinceName in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotIn(List<String> values) {
            addCriterion("ProvinceName not in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameBetween(String value1, String value2) {
            addCriterion("ProvinceName between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotBetween(String value1, String value2) {
            addCriterion("ProvinceName not between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("CityName is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("CityName is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("CityName =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("CityName <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("CityName >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("CityName >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("CityName <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("CityName <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("CityName like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("CityName not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("CityName in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("CityName not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("CityName between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("CityName not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andPositionDataIsNull() {
            addCriterion("PositionData is null");
            return (Criteria) this;
        }

        public Criteria andPositionDataIsNotNull() {
            addCriterion("PositionData is not null");
            return (Criteria) this;
        }

        public Criteria andPositionDataEqualTo(String value) {
            addCriterion("PositionData =", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataNotEqualTo(String value) {
            addCriterion("PositionData <>", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataGreaterThan(String value) {
            addCriterion("PositionData >", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataGreaterThanOrEqualTo(String value) {
            addCriterion("PositionData >=", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataLessThan(String value) {
            addCriterion("PositionData <", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataLessThanOrEqualTo(String value) {
            addCriterion("PositionData <=", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataLike(String value) {
            addCriterion("PositionData like", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataNotLike(String value) {
            addCriterion("PositionData not like", value, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataIn(List<String> values) {
            addCriterion("PositionData in", values, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataNotIn(List<String> values) {
            addCriterion("PositionData not in", values, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataBetween(String value1, String value2) {
            addCriterion("PositionData between", value1, value2, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionDataNotBetween(String value1, String value2) {
            addCriterion("PositionData not between", value1, value2, "positionData");
            return (Criteria) this;
        }

        public Criteria andPositionXIsNull() {
            addCriterion("PositionX is null");
            return (Criteria) this;
        }

        public Criteria andPositionXIsNotNull() {
            addCriterion("PositionX is not null");
            return (Criteria) this;
        }

        public Criteria andPositionXEqualTo(Double value) {
            addCriterion("PositionX =", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotEqualTo(Double value) {
            addCriterion("PositionX <>", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXGreaterThan(Double value) {
            addCriterion("PositionX >", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXGreaterThanOrEqualTo(Double value) {
            addCriterion("PositionX >=", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXLessThan(Double value) {
            addCriterion("PositionX <", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXLessThanOrEqualTo(Double value) {
            addCriterion("PositionX <=", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXIn(List<Double> values) {
            addCriterion("PositionX in", values, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotIn(List<Double> values) {
            addCriterion("PositionX not in", values, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXBetween(Double value1, Double value2) {
            addCriterion("PositionX between", value1, value2, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotBetween(Double value1, Double value2) {
            addCriterion("PositionX not between", value1, value2, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionYIsNull() {
            addCriterion("PositionY is null");
            return (Criteria) this;
        }

        public Criteria andPositionYIsNotNull() {
            addCriterion("PositionY is not null");
            return (Criteria) this;
        }

        public Criteria andPositionYEqualTo(Double value) {
            addCriterion("PositionY =", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotEqualTo(Double value) {
            addCriterion("PositionY <>", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYGreaterThan(Double value) {
            addCriterion("PositionY >", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYGreaterThanOrEqualTo(Double value) {
            addCriterion("PositionY >=", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYLessThan(Double value) {
            addCriterion("PositionY <", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYLessThanOrEqualTo(Double value) {
            addCriterion("PositionY <=", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYIn(List<Double> values) {
            addCriterion("PositionY in", values, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotIn(List<Double> values) {
            addCriterion("PositionY not in", values, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYBetween(Double value1, Double value2) {
            addCriterion("PositionY between", value1, value2, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotBetween(Double value1, Double value2) {
            addCriterion("PositionY not between", value1, value2, "positionY");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNull() {
            addCriterion("AppVersion is null");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNotNull() {
            addCriterion("AppVersion is not null");
            return (Criteria) this;
        }

        public Criteria andAppVersionEqualTo(String value) {
            addCriterion("AppVersion =", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotEqualTo(String value) {
            addCriterion("AppVersion <>", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThan(String value) {
            addCriterion("AppVersion >", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("AppVersion >=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThan(String value) {
            addCriterion("AppVersion <", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThanOrEqualTo(String value) {
            addCriterion("AppVersion <=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLike(String value) {
            addCriterion("AppVersion like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotLike(String value) {
            addCriterion("AppVersion not like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionIn(List<String> values) {
            addCriterion("AppVersion in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotIn(List<String> values) {
            addCriterion("AppVersion not in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionBetween(String value1, String value2) {
            addCriterion("AppVersion between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotBetween(String value1, String value2) {
            addCriterion("AppVersion not between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNull() {
            addCriterion("platformId is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNotNull() {
            addCriterion("platformId is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdEqualTo(Integer value) {
            addCriterion("platformId =", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotEqualTo(Integer value) {
            addCriterion("platformId <>", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThan(Integer value) {
            addCriterion("platformId >", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("platformId >=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThan(Integer value) {
            addCriterion("platformId <", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThanOrEqualTo(Integer value) {
            addCriterion("platformId <=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIn(List<Integer> values) {
            addCriterion("platformId in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotIn(List<Integer> values) {
            addCriterion("platformId not in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdBetween(Integer value1, Integer value2) {
            addCriterion("platformId between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotBetween(Integer value1, Integer value2) {
            addCriterion("platformId not between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIsNull() {
            addCriterion("PhoneBrand is null");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIsNotNull() {
            addCriterion("PhoneBrand is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandEqualTo(String value) {
            addCriterion("PhoneBrand =", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotEqualTo(String value) {
            addCriterion("PhoneBrand <>", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandGreaterThan(String value) {
            addCriterion("PhoneBrand >", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandGreaterThanOrEqualTo(String value) {
            addCriterion("PhoneBrand >=", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLessThan(String value) {
            addCriterion("PhoneBrand <", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLessThanOrEqualTo(String value) {
            addCriterion("PhoneBrand <=", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandLike(String value) {
            addCriterion("PhoneBrand like", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotLike(String value) {
            addCriterion("PhoneBrand not like", value, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandIn(List<String> values) {
            addCriterion("PhoneBrand in", values, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotIn(List<String> values) {
            addCriterion("PhoneBrand not in", values, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandBetween(String value1, String value2) {
            addCriterion("PhoneBrand between", value1, value2, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneBrandNotBetween(String value1, String value2) {
            addCriterion("PhoneBrand not between", value1, value2, "phoneBrand");
            return (Criteria) this;
        }

        public Criteria andPhoneModelIsNull() {
            addCriterion("PhoneModel is null");
            return (Criteria) this;
        }

        public Criteria andPhoneModelIsNotNull() {
            addCriterion("PhoneModel is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneModelEqualTo(String value) {
            addCriterion("PhoneModel =", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelNotEqualTo(String value) {
            addCriterion("PhoneModel <>", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelGreaterThan(String value) {
            addCriterion("PhoneModel >", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelGreaterThanOrEqualTo(String value) {
            addCriterion("PhoneModel >=", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelLessThan(String value) {
            addCriterion("PhoneModel <", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelLessThanOrEqualTo(String value) {
            addCriterion("PhoneModel <=", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelLike(String value) {
            addCriterion("PhoneModel like", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelNotLike(String value) {
            addCriterion("PhoneModel not like", value, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelIn(List<String> values) {
            addCriterion("PhoneModel in", values, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelNotIn(List<String> values) {
            addCriterion("PhoneModel not in", values, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelBetween(String value1, String value2) {
            addCriterion("PhoneModel between", value1, value2, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andPhoneModelNotBetween(String value1, String value2) {
            addCriterion("PhoneModel not between", value1, value2, "phoneModel");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNull() {
            addCriterion("OperatorName is null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNotNull() {
            addCriterion("OperatorName is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameEqualTo(String value) {
            addCriterion("OperatorName =", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotEqualTo(String value) {
            addCriterion("OperatorName <>", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThan(String value) {
            addCriterion("OperatorName >", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("OperatorName >=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThan(String value) {
            addCriterion("OperatorName <", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThanOrEqualTo(String value) {
            addCriterion("OperatorName <=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLike(String value) {
            addCriterion("OperatorName like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotLike(String value) {
            addCriterion("OperatorName not like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIn(List<String> values) {
            addCriterion("OperatorName in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotIn(List<String> values) {
            addCriterion("OperatorName not in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameBetween(String value1, String value2) {
            addCriterion("OperatorName between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotBetween(String value1, String value2) {
            addCriterion("OperatorName not between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionIsNull() {
            addCriterion("PhoneVersion is null");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionIsNotNull() {
            addCriterion("PhoneVersion is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionEqualTo(String value) {
            addCriterion("PhoneVersion =", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionNotEqualTo(String value) {
            addCriterion("PhoneVersion <>", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionGreaterThan(String value) {
            addCriterion("PhoneVersion >", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionGreaterThanOrEqualTo(String value) {
            addCriterion("PhoneVersion >=", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionLessThan(String value) {
            addCriterion("PhoneVersion <", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionLessThanOrEqualTo(String value) {
            addCriterion("PhoneVersion <=", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionLike(String value) {
            addCriterion("PhoneVersion like", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionNotLike(String value) {
            addCriterion("PhoneVersion not like", value, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionIn(List<String> values) {
            addCriterion("PhoneVersion in", values, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionNotIn(List<String> values) {
            addCriterion("PhoneVersion not in", values, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionBetween(String value1, String value2) {
            addCriterion("PhoneVersion between", value1, value2, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andPhoneVersionNotBetween(String value1, String value2) {
            addCriterion("PhoneVersion not between", value1, value2, "phoneVersion");
            return (Criteria) this;
        }

        public Criteria andNetModelIsNull() {
            addCriterion("NetModel is null");
            return (Criteria) this;
        }

        public Criteria andNetModelIsNotNull() {
            addCriterion("NetModel is not null");
            return (Criteria) this;
        }

        public Criteria andNetModelEqualTo(String value) {
            addCriterion("NetModel =", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelNotEqualTo(String value) {
            addCriterion("NetModel <>", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelGreaterThan(String value) {
            addCriterion("NetModel >", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelGreaterThanOrEqualTo(String value) {
            addCriterion("NetModel >=", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelLessThan(String value) {
            addCriterion("NetModel <", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelLessThanOrEqualTo(String value) {
            addCriterion("NetModel <=", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelLike(String value) {
            addCriterion("NetModel like", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelNotLike(String value) {
            addCriterion("NetModel not like", value, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelIn(List<String> values) {
            addCriterion("NetModel in", values, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelNotIn(List<String> values) {
            addCriterion("NetModel not in", values, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelBetween(String value1, String value2) {
            addCriterion("NetModel between", value1, value2, "netModel");
            return (Criteria) this;
        }

        public Criteria andNetModelNotBetween(String value1, String value2) {
            addCriterion("NetModel not between", value1, value2, "netModel");
            return (Criteria) this;
        }

        public Criteria andIpAddressIsNull() {
            addCriterion("IpAddress is null");
            return (Criteria) this;
        }

        public Criteria andIpAddressIsNotNull() {
            addCriterion("IpAddress is not null");
            return (Criteria) this;
        }

        public Criteria andIpAddressEqualTo(String value) {
            addCriterion("IpAddress =", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotEqualTo(String value) {
            addCriterion("IpAddress <>", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressGreaterThan(String value) {
            addCriterion("IpAddress >", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("IpAddress >=", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLessThan(String value) {
            addCriterion("IpAddress <", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLessThanOrEqualTo(String value) {
            addCriterion("IpAddress <=", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressLike(String value) {
            addCriterion("IpAddress like", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotLike(String value) {
            addCriterion("IpAddress not like", value, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressIn(List<String> values) {
            addCriterion("IpAddress in", values, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotIn(List<String> values) {
            addCriterion("IpAddress not in", values, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressBetween(String value1, String value2) {
            addCriterion("IpAddress between", value1, value2, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpAddressNotBetween(String value1, String value2) {
            addCriterion("IpAddress not between", value1, value2, "ipAddress");
            return (Criteria) this;
        }

        public Criteria andIpPositionIsNull() {
            addCriterion("IpPosition is null");
            return (Criteria) this;
        }

        public Criteria andIpPositionIsNotNull() {
            addCriterion("IpPosition is not null");
            return (Criteria) this;
        }

        public Criteria andIpPositionEqualTo(String value) {
            addCriterion("IpPosition =", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionNotEqualTo(String value) {
            addCriterion("IpPosition <>", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionGreaterThan(String value) {
            addCriterion("IpPosition >", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionGreaterThanOrEqualTo(String value) {
            addCriterion("IpPosition >=", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionLessThan(String value) {
            addCriterion("IpPosition <", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionLessThanOrEqualTo(String value) {
            addCriterion("IpPosition <=", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionLike(String value) {
            addCriterion("IpPosition like", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionNotLike(String value) {
            addCriterion("IpPosition not like", value, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionIn(List<String> values) {
            addCriterion("IpPosition in", values, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionNotIn(List<String> values) {
            addCriterion("IpPosition not in", values, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionBetween(String value1, String value2) {
            addCriterion("IpPosition between", value1, value2, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIpPositionNotBetween(String value1, String value2) {
            addCriterion("IpPosition not between", value1, value2, "ipPosition");
            return (Criteria) this;
        }

        public Criteria andIdfaIsNull() {
            addCriterion("Idfa is null");
            return (Criteria) this;
        }

        public Criteria andIdfaIsNotNull() {
            addCriterion("Idfa is not null");
            return (Criteria) this;
        }

        public Criteria andIdfaEqualTo(String value) {
            addCriterion("Idfa =", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotEqualTo(String value) {
            addCriterion("Idfa <>", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaGreaterThan(String value) {
            addCriterion("Idfa >", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaGreaterThanOrEqualTo(String value) {
            addCriterion("Idfa >=", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLessThan(String value) {
            addCriterion("Idfa <", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLessThanOrEqualTo(String value) {
            addCriterion("Idfa <=", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLike(String value) {
            addCriterion("Idfa like", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotLike(String value) {
            addCriterion("Idfa not like", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaIn(List<String> values) {
            addCriterion("Idfa in", values, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotIn(List<String> values) {
            addCriterion("Idfa not in", values, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaBetween(String value1, String value2) {
            addCriterion("Idfa between", value1, value2, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotBetween(String value1, String value2) {
            addCriterion("Idfa not between", value1, value2, "idfa");
            return (Criteria) this;
        }

        public Criteria andOpenudidIsNull() {
            addCriterion("Openudid is null");
            return (Criteria) this;
        }

        public Criteria andOpenudidIsNotNull() {
            addCriterion("Openudid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenudidEqualTo(String value) {
            addCriterion("Openudid =", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidNotEqualTo(String value) {
            addCriterion("Openudid <>", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidGreaterThan(String value) {
            addCriterion("Openudid >", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidGreaterThanOrEqualTo(String value) {
            addCriterion("Openudid >=", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidLessThan(String value) {
            addCriterion("Openudid <", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidLessThanOrEqualTo(String value) {
            addCriterion("Openudid <=", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidLike(String value) {
            addCriterion("Openudid like", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidNotLike(String value) {
            addCriterion("Openudid not like", value, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidIn(List<String> values) {
            addCriterion("Openudid in", values, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidNotIn(List<String> values) {
            addCriterion("Openudid not in", values, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidBetween(String value1, String value2) {
            addCriterion("Openudid between", value1, value2, "openudid");
            return (Criteria) this;
        }

        public Criteria andOpenudidNotBetween(String value1, String value2) {
            addCriterion("Openudid not between", value1, value2, "openudid");
            return (Criteria) this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("Imei is null");
            return (Criteria) this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("Imei is not null");
            return (Criteria) this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("Imei =", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("Imei <>", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("Imei >", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("Imei >=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("Imei <", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("Imei <=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("Imei like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("Imei not like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiIn(List<String> values) {
            addCriterion("Imei in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotIn(List<String> values) {
            addCriterion("Imei not in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("Imei between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("Imei not between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andMacAddressIsNull() {
            addCriterion("MacAddress is null");
            return (Criteria) this;
        }

        public Criteria andMacAddressIsNotNull() {
            addCriterion("MacAddress is not null");
            return (Criteria) this;
        }

        public Criteria andMacAddressEqualTo(String value) {
            addCriterion("MacAddress =", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressNotEqualTo(String value) {
            addCriterion("MacAddress <>", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressGreaterThan(String value) {
            addCriterion("MacAddress >", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MacAddress >=", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressLessThan(String value) {
            addCriterion("MacAddress <", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressLessThanOrEqualTo(String value) {
            addCriterion("MacAddress <=", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressLike(String value) {
            addCriterion("MacAddress like", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressNotLike(String value) {
            addCriterion("MacAddress not like", value, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressIn(List<String> values) {
            addCriterion("MacAddress in", values, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressNotIn(List<String> values) {
            addCriterion("MacAddress not in", values, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressBetween(String value1, String value2) {
            addCriterion("MacAddress between", value1, value2, "macAddress");
            return (Criteria) this;
        }

        public Criteria andMacAddressNotBetween(String value1, String value2) {
            addCriterion("MacAddress not between", value1, value2, "macAddress");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LastUpdateTime =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LastUpdateTime <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LastUpdateTime >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LastUpdateTime <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("LastUpdateTime in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("LastUpdateTime not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeIsNull() {
            addCriterion("OperatorCode is null");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeIsNotNull() {
            addCriterion("OperatorCode is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeEqualTo(String value) {
            addCriterion("OperatorCode =", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeNotEqualTo(String value) {
            addCriterion("OperatorCode <>", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeGreaterThan(String value) {
            addCriterion("OperatorCode >", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OperatorCode >=", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeLessThan(String value) {
            addCriterion("OperatorCode <", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeLessThanOrEqualTo(String value) {
            addCriterion("OperatorCode <=", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeLike(String value) {
            addCriterion("OperatorCode like", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeNotLike(String value) {
            addCriterion("OperatorCode not like", value, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeIn(List<String> values) {
            addCriterion("OperatorCode in", values, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeNotIn(List<String> values) {
            addCriterion("OperatorCode not in", values, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeBetween(String value1, String value2) {
            addCriterion("OperatorCode between", value1, value2, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andOperatorCodeNotBetween(String value1, String value2) {
            addCriterion("OperatorCode not between", value1, value2, "operatorCode");
            return (Criteria) this;
        }

        public Criteria andCpuabiIsNull() {
            addCriterion("Cpuabi is null");
            return (Criteria) this;
        }

        public Criteria andCpuabiIsNotNull() {
            addCriterion("Cpuabi is not null");
            return (Criteria) this;
        }

        public Criteria andCpuabiEqualTo(String value) {
            addCriterion("Cpuabi =", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiNotEqualTo(String value) {
            addCriterion("Cpuabi <>", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiGreaterThan(String value) {
            addCriterion("Cpuabi >", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiGreaterThanOrEqualTo(String value) {
            addCriterion("Cpuabi >=", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiLessThan(String value) {
            addCriterion("Cpuabi <", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiLessThanOrEqualTo(String value) {
            addCriterion("Cpuabi <=", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiLike(String value) {
            addCriterion("Cpuabi like", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiNotLike(String value) {
            addCriterion("Cpuabi not like", value, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiIn(List<String> values) {
            addCriterion("Cpuabi in", values, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiNotIn(List<String> values) {
            addCriterion("Cpuabi not in", values, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiBetween(String value1, String value2) {
            addCriterion("Cpuabi between", value1, value2, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andCpuabiNotBetween(String value1, String value2) {
            addCriterion("Cpuabi not between", value1, value2, "cpuabi");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorIsNull() {
            addCriterion("IsEmulator is null");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorIsNotNull() {
            addCriterion("IsEmulator is not null");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorEqualTo(Boolean value) {
            addCriterion("IsEmulator =", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorNotEqualTo(Boolean value) {
            addCriterion("IsEmulator <>", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorGreaterThan(Boolean value) {
            addCriterion("IsEmulator >", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsEmulator >=", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorLessThan(Boolean value) {
            addCriterion("IsEmulator <", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorLessThanOrEqualTo(Boolean value) {
            addCriterion("IsEmulator <=", value, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorIn(List<Boolean> values) {
            addCriterion("IsEmulator in", values, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorNotIn(List<Boolean> values) {
            addCriterion("IsEmulator not in", values, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorBetween(Boolean value1, Boolean value2) {
            addCriterion("IsEmulator between", value1, value2, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsEmulatorNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsEmulator not between", value1, value2, "isEmulator");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakIsNull() {
            addCriterion("IsJailbreak is null");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakIsNotNull() {
            addCriterion("IsJailbreak is not null");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakEqualTo(Boolean value) {
            addCriterion("IsJailbreak =", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakNotEqualTo(Boolean value) {
            addCriterion("IsJailbreak <>", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakGreaterThan(Boolean value) {
            addCriterion("IsJailbreak >", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsJailbreak >=", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakLessThan(Boolean value) {
            addCriterion("IsJailbreak <", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakLessThanOrEqualTo(Boolean value) {
            addCriterion("IsJailbreak <=", value, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakIn(List<Boolean> values) {
            addCriterion("IsJailbreak in", values, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakNotIn(List<Boolean> values) {
            addCriterion("IsJailbreak not in", values, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakBetween(Boolean value1, Boolean value2) {
            addCriterion("IsJailbreak between", value1, value2, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andIsJailbreakNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsJailbreak not between", value1, value2, "isJailbreak");
            return (Criteria) this;
        }

        public Criteria andImsiIsNull() {
            addCriterion("Imsi is null");
            return (Criteria) this;
        }

        public Criteria andImsiIsNotNull() {
            addCriterion("Imsi is not null");
            return (Criteria) this;
        }

        public Criteria andImsiEqualTo(String value) {
            addCriterion("Imsi =", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotEqualTo(String value) {
            addCriterion("Imsi <>", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiGreaterThan(String value) {
            addCriterion("Imsi >", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiGreaterThanOrEqualTo(String value) {
            addCriterion("Imsi >=", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLessThan(String value) {
            addCriterion("Imsi <", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLessThanOrEqualTo(String value) {
            addCriterion("Imsi <=", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLike(String value) {
            addCriterion("Imsi like", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotLike(String value) {
            addCriterion("Imsi not like", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiIn(List<String> values) {
            addCriterion("Imsi in", values, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotIn(List<String> values) {
            addCriterion("Imsi not in", values, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiBetween(String value1, String value2) {
            addCriterion("Imsi between", value1, value2, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotBetween(String value1, String value2) {
            addCriterion("Imsi not between", value1, value2, "imsi");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_device
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 29 10:12:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_device
     *
     * @mbg.generated Sat Sep 29 10:12:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}