package com.treefinance.saas.taskcenter.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskPoint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.task_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Long task_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.unique_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Long unique_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.type
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.code
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.sub_step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String sub_step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.msg
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.remake
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String remake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.ip
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.occur_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Date occur_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.create_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_point.last_update_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private Date last_update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_point
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.id
     *
     * @return the value of task_point.id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.id
     *
     * @param id the value for task_point.id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.task_id
     *
     * @return the value of task_point.task_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Long getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.task_id
     *
     * @param task_id the value for task_point.task_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setTask_id(Long task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.unique_id
     *
     * @return the value of task_point.unique_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Long getUnique_id() {
        return unique_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.unique_id
     *
     * @param unique_id the value for task_point.unique_id
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setUnique_id(Long unique_id) {
        this.unique_id = unique_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.type
     *
     * @return the value of task_point.type
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.type
     *
     * @param type the value for task_point.type
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.code
     *
     * @return the value of task_point.code
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.code
     *
     * @param code the value for task_point.code
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.step
     *
     * @return the value of task_point.step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.step
     *
     * @param step the value for task_point.step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.sub_step
     *
     * @return the value of task_point.sub_step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getSub_step() {
        return sub_step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.sub_step
     *
     * @param sub_step the value for task_point.sub_step
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setSub_step(String sub_step) {
        this.sub_step = sub_step == null ? null : sub_step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.msg
     *
     * @return the value of task_point.msg
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.msg
     *
     * @param msg the value for task_point.msg
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.remake
     *
     * @return the value of task_point.remake
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.remake
     *
     * @param remake the value for task_point.remake
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.ip
     *
     * @return the value of task_point.ip
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.ip
     *
     * @param ip the value for task_point.ip
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.occur_time
     *
     * @return the value of task_point.occur_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Date getOccur_time() {
        return occur_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.occur_time
     *
     * @param occur_time the value for task_point.occur_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setOccur_time(Date occur_time) {
        this.occur_time = occur_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.create_time
     *
     * @return the value of task_point.create_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.create_time
     *
     * @param create_time the value for task_point.create_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_point.last_update_time
     *
     * @return the value of task_point.last_update_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public Date getLast_update_time() {
        return last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_point.last_update_time
     *
     * @param last_update_time the value for task_point.last_update_time
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    public void setLast_update_time(Date last_update_time) {
        this.last_update_time = last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_point
     *
     * @mbg.generated Tue Jan 22 14:35:17 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", task_id=").append(task_id);
        sb.append(", unique_id=").append(unique_id);
        sb.append(", type=").append(type);
        sb.append(", code=").append(code);
        sb.append(", step=").append(step);
        sb.append(", sub_step=").append(sub_step);
        sb.append(", msg=").append(msg);
        sb.append(", remake=").append(remake);
        sb.append(", ip=").append(ip);
        sb.append(", occur_time=").append(occur_time);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_update_time=").append(last_update_time);
        sb.append("]");
        return sb.toString();
    }
}